//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDirectoryAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public string EmployeeNo { get; set; }
        public string PersonalEmail { get; set; }
        public string FullName { get; set; }
        public string OfficialEmail { get; set; }
        public string Mobile { get; set; }
        public string ContactPhone { get; set; }
        public string Ext { get; set; }
    
    }
}
